[tool.poetry]
name = "saltybet-asyncio"
version = "0.1.0"
description = ""
authors = ["Nick Pancakes <nick@pncks.com>"]

[tool.poetry.dependencies]
python = "^3.7"
python-socketio = {extras = ["asyncio_client"], version = "^4.6.0"}
aiorun = "^2020.6.1"
aiosqlite = "^0.14.1"
selectolax = "^0.2.10"
html5print = "^0.1.2"
pendulum = "^2.1.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^19.10b0"
pylint = "^2.5.3"
ipdb = "^0.13.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
